version: '{build}'
image: Visual Studio 2019
environment:
  nuget_key:
    secure: DviconFZ6G3ZX9Q9XktXy0SRmOXmd//stfYVnzYvniBP/JBzZ6y2gjJjEZhALyk4
build_script:
  - ps: ./build.ps1
test: off # tests are run by build_script
deploy_script:
  - ps: ./build.ps1 -Target Release
