version: '{build}'
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
environment:
  nuget_key:
    secure: DviconFZ6G3ZX9Q9XktXy0SRmOXmd//stfYVnzYvniBP/JBzZ6y2gjJjEZhALyk4
build_script:
- ps: ./build
test: off
deploy_script:
- ps: ./build -Target Release
